### ISSUE TITLE
Distinct filter not correctly applied to ISIS endpoints

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway-api#114]
Applying a distinct filter to the ISIS endpoints returns all of the entities of that type rather than being filtered by instrument and/or facilityCycle.

e.g. querying `http://scigateway-preprod.esc.rl.ac.uk:5000/instruments/1/facilitycycles/14/investigations?distinct="ID"`

Returns all investigation IDs, instead of the correct results for that facility cycle and investigation, which would just be `[{"ID": 89}]`

**Comment by MRichards99** [comment]
The PR associated with this issue has been reviewed and merged, but because it hasn't been merged into master, it hasn't been closed automatically, but the work for this issue has been completed.
