### ISSUE TITLE
Casing of JSON fields is not consistent with ICAT API

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway-api#119]
Since ICAT is written in Java, it uses `camelCase` for it's JSON field names when querying entities. However, `datagateway-api` uses `SNAKE_CASE` since it reflects the database column names. This will cause incompatibilities when datagateway switches over from accessing this to the new ICAT API.

Acceptance criteria:
- [ ] Return objects match what ICAT returns w.r.t. casing

**Comment by MRichards99** [comment]
As above, this is fixed in the new ICAT backend. However, since the two backends should behave in the same way, SNAKE_CASE in the DB backend should also use the camelCase so the two backends can be interchanged.
