### ISSUE TITLE
implement ISIS-specific endpoints for python-icat

### ISSUE THREAD

**Issue by stuartpullinger** [ral-facilities/datagateway-api#146]
- [ ]  get_instrument_facilitycycles_with_filters
- [ ]  count_instrument_facilitycycles_with_filters
- [ ] get_instrument_facilitycycle_investigations_with_filters
- [ ]  count_instrument_facilitycycles_investigations_with_filters

**Comment by MRichards99** [comment]
The PR associated with this issue has been reviewed and merged, but because it hasn't been merged into master, it hasn't been closed automatically, but the work for this issue has been completed.
