### ISSUE TITLE
Fix exception handling

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway-api#147]
Currently, the custom error handling only works in debug mode. This is due to some behaviour about propagating exceptions. However, in production mode `flask-restful` intercepts the exceptions before our custom flask ones can handle them. See: https://flask-restful.readthedocs.io/en/latest/extending.html#custom-error-handlers.

We should either define a custom dictionary like the docs recommend, or instead implement our "own" API and override the `handle_error` function like detailed in these answers: https://stackoverflow.com/questions/41149409/flask-restful-custom-error-handling

Acceptance criteria:
- [x] Our custom exceptions should return the correct error codes to the user in both debug + production mode

**Comment by MRichards99** [comment]
The PR associated with this issue has been reviewed and merged, but because it hasn't been merged into master, it hasn't been closed automatically, but the work for this issue has been completed.
