### ISSUE TITLE
Don't write to openapi.yaml at runtime

### ISSUE THREAD

**Issue by ajkyffin** [ral-facilities/datagateway-api#183]
The file openapi.yaml is written when the application is started. This is problem in production because it will be in a read-only directory.

If it needs to be written at startup, then its location should be configurable so that is can be put in /run. However, it looks like the version in the repository is fine and there's no need to write it.

**Comment by MRichards99** [comment]
The PR associated with this issue has been reviewed and merged, but because it hasn't been merged into master, it hasn't been closed automatically, but the work for this issue has been completed.
