### ISSUE TITLE
Add python-icat & suds-community to requirements.in

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway-api#195]
**Description**:
I just tried deploying master on scigateway-preprod, and had some problems with not having python-icat (and it's sub-dependency suds-community) installed. These should be added to the requirements files.

**Acceptance criteria**:
- [ ] Requirements files up to date

**Comment by MRichards99** [comment]
Now this repo has been moved over to use Poetry to track its dependencies, the `pyproject.toml` file contains these dependencies, pinned to specific versions. See:
https://github.com/ral-facilities/datagateway-api/blob/feature/remove-sql-dependency-from-backends-%23154/pyproject.toml#L20

Once the remaining PRs are merged into master, this should get fixed.

**Comment by louise-davies** [comment]
Ah yeah, forgot we had a new dependency management system - no worries then!
