### ISSUE TITLE
Write Tests to Cover Example Queries

### ISSUE THREAD

**Issue by MRichards99** [ral-facilities/datagateway-api#270]
**Description**:
The documentation details a number of example queries, for [dataset](https://github.com/panosc-eu/search-api/blob/master/doc/dataset-example-queries.md), [document](https://github.com/panosc-eu/search-api/blob/master/doc/document-example-queries.md) and [instrument](https://github.com/panosc-eu/search-api/blob/master/doc/instrument-example-queries.md) endpoints. We should write tests to cover these (using Flask's test client like in `test/icat/endpoints/test_findone.py`). I'm not sure whether we'll be able to replicate the exact data they use (stored in a [json file](https://github.com/panosc-eu/search-api/blob/master/data/db.json) which I guess gets loaded in somewhere) but we should at least demonstrate that the functionality demonstrated in those examples does work. If we had to use their data for that, I guess you could write a script using that json file and create the data in ICAT (perhaps using the PaNOSC data model modelled in the repo with classes?).

**Acceptance criteria**:
- [ ] Write tests using Flask test client to show the functionality in the example queries works in our implementation

**Comment by VKTB** [comment]
✔️ - Yes
:x: - No
| Example query                                                                                                                                                                                                                                  | Requires ICAT 5    | Any other endpoint level tests with such filter structure already in place | Notes                                                                                                                                                                                                                                                                                                                                |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------|----------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [Query datasets acquired using X-Ray Absorption](https://github.com/panosc-eu/search-api/blob/master/doc/dataset-example-queries.md#query-datasets-acquired-using-x-ray-absorption)                                                            | :heavy_check_mark: | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
| [Query datasets where the photon energy range is 880-990 eV](https://github.com/panosc-eu/search-api/blob/master/doc/dataset-example-queries.md#query-datasets-where-the-photon-energy-range-is-880-990-ev)                                    | :x:                | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
| [Query datasets with a solid sample or copper](https://github.com/panosc-eu/search-api/blob/master/doc/dataset-example-queries.md#query-datasets-with-a-solid-sample-or-copper)                                                                | :x:                | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
| [Query datasets where temperature is below 80°C](https://github.com/panosc-eu/search-api/blob/master/doc/dataset-example-queries.md#query-datasets-where-temperature-is-below-80c)                                                             | :x:                | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
| [Query datasets with files matching a string using full text search](https://github.com/panosc-eu/search-api/blob/master/doc/dataset-example-queries.md#query-datasets-with-files-matching-a-string-using-full-text-search)                    | :x:                | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
| [Query documents of type proposal containing my own data](https://github.com/panosc-eu/search-api/blob/master/doc/document-example-queries.md#query-documents-of-type-proposal-containing-my-own-data)                                         | :x:                | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
| [Query documents where wavelength is 1000-1100 nm](https://github.com/panosc-eu/search-api/blob/master/doc/document-example-queries.md#query-documents-where-wavelength-is-1000-1100-nm)                                                       | :x:                | :x:                                                                        | The filter has the same structure as the [Query datasets where the photon energy range is 880-990 eV](https://github.com/panosc-eu/search-api/blob/master/doc/dataset-example-queries.md#query-datasets-where-the-photon-energy-range-is-880-990-ev) example query so writing a test for one of the cases should probably be enough. |
| [Query documents containing datasets where wavelength is 1000-1100 nm](https://github.com/panosc-eu/search-api/blob/master/doc/document-example-queries.md#query-documents-containing-datasets-where-wavelength-is-1000-1100-nm)               | :x:                | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
| [Query documents investigating a particular sample using a certain technique](https://github.com/panosc-eu/search-api/blob/master/doc/document-example-queries.md#query-documents-investigating-a-particular-sample-using-a-certain-technique) | :heavy_check_mark: | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |

**Comment by VKTB** [comment]
I had a look at our endpoint tests and discovered that we do not have tests for the below example queries. Please note that we test filters with structures as the ones in the below example queries at a `SearchAPIQueryFilterFactory`, `NestedWhereFilters` etc. class level but not an endpoint level.

✔️ - Yes
:x: - No
| Example query                                                                                                                                                                                                                                  | Requires ICAT 5    | Any other endpoint level tests with such filter structure already in place | Notes                                                                                                                                                                                                                                                                                                                                |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------|----------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [Query datasets acquired using X-Ray Absorption](https://github.com/panosc-eu/search-api/blob/master/doc/dataset-example-queries.md#query-datasets-acquired-using-x-ray-absorption)                                                            | :heavy_check_mark: | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
| [Query datasets where the photon energy range is 880-990 eV](https://github.com/panosc-eu/search-api/blob/master/doc/dataset-example-queries.md#query-datasets-where-the-photon-energy-range-is-880-990-ev)                                    | :x:                | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
| [Query datasets with a solid sample or copper](https://github.com/panosc-eu/search-api/blob/master/doc/dataset-example-queries.md#query-datasets-with-a-solid-sample-or-copper)                                                                | :x:                | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
| [Query datasets where temperature is below 80°C](https://github.com/panosc-eu/search-api/blob/master/doc/dataset-example-queries.md#query-datasets-where-temperature-is-below-80c)                                                             | :x:                | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
| [Query datasets with files matching a string using full text search](https://github.com/panosc-eu/search-api/blob/master/doc/dataset-example-queries.md#query-datasets-with-files-matching-a-string-using-full-text-search)                    | :x:                | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
| [Query documents of type proposal containing my own data](https://github.com/panosc-eu/search-api/blob/master/doc/document-example-queries.md#query-documents-of-type-proposal-containing-my-own-data)                                         | :x:                | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
| [Query documents where wavelength is 1000-1100 nm](https://github.com/panosc-eu/search-api/blob/master/doc/document-example-queries.md#query-documents-where-wavelength-is-1000-1100-nm)                                                       | :x:                | :x:                                                                        | The filter has the same structure as the [Query datasets where the photon energy range is 880-990 eV](https://github.com/panosc-eu/search-api/blob/master/doc/dataset-example-queries.md#query-datasets-where-the-photon-energy-range-is-880-990-ev) example query so writing a test for one of the cases should probably be enough. |
| [Query documents containing datasets where wavelength is 1000-1100 nm](https://github.com/panosc-eu/search-api/blob/master/doc/document-example-queries.md#query-documents-containing-datasets-where-wavelength-is-1000-1100-nm)               | :x:                | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
| [Query documents investigating a particular sample using a certain technique](https://github.com/panosc-eu/search-api/blob/master/doc/document-example-queries.md#query-documents-investigating-a-particular-sample-using-a-certain-technique) | :heavy_check_mark: | :x:                                                                        |                                                                                                                                                                                                                                                                                                                                      |
