### ISSUE TITLE
Nox tests session failing to set up on Windows

### ISSUE THREAD

**Issue by VKTB** [ral-facilities/datagateway-api#307]
**Description**:
The `nox` `tests` session is falling to set up on Windows. It looks like, the problem is on this line https://github.com/ral-facilities/datagateway-api/blob/c4bd953f76b726f91e3b9ecb2ae6d8eaa13ac991/noxfile.py#L98

Terminal logs:
```
nox > Re-using existing virtual environment at .nox\tests-3-6.
nox > poetry run pip uninstall -y setuptools
WARNING: Skipping setuptools as it is not installed.
poetry run pip install setuptools<58.0.0
The system cannot find the file specified.
Command poetry run pip install setuptools<58.0.0 failed with exit code 1
Session tests-3.6 failed.
```

This happens for all the python versions.

**Acceptance criteria**:
- [ ] The `nox` `tests` session should successfully set up on Windows

**Comment by VKTB** [comment]
I looked at this again but I could not figure out what's causing the issue. During my trial and error, I discovered that changing line 98 to the below solves this issue:
`session.run("pip", "install", "setuptools<58.0.0")`

However, I cannot tell whether not using `poetry` to install `setuptools` has any undesired effects. @MRichards99 are you aware of any issues that installing it this way may cause?

**Comment by MRichards99** [comment]
I've just tested this on my machine and found no issues - in fact it removes a warning that was occurring with using Poetry run. If you could make the change, that would be great
