### ISSUE TITLE
Return 404 on /files and /files/count endpoints with non-existent dataset pid

### ISSUE THREAD

**Issue by VKTB** [ral-facilities/datagateway-api#327]
**Description**:
Sending the following requests:
`http://{{datagateway-api}}/search-api/datasets/invalid pid/files`
`http://{{datagateway-api}}/search-api/datasets/invalid pid/files/count`
return `200 OK`:
```
[]
```

when in fact they should return `404 NOT FOUND`, just like when you send the following request:
`http://{{datagateway-api}}/search-api/datasets/invalid pid/`.

**Acceptance criteria**:
- [ ] Requests to `/files` endpoint with non-existent dataset `pid` should return `404`
- [ ] Requests to `/files/count` endpoint with non-existent dataset `pid` should return `404`
- [ ] Unskip the following test https://github.com/ral-facilities/datagateway-api/blob/11d59e869f2945e697582d2f55a50a931730bd9b/test/search_api/endpoints/test_get_dataset_files.py#L144-L151
- [ ] Add a test to cover `404` on `/files/count` endpoint with non-existent dataset `pid`

**Comment by VKTB** [comment]
If we call `get_with_pid` at the the begging of the `get_files` and `get_files_count` methods then that addresses this bug. Conscious that this would result in multiple calls to ICAT but it does the job. @MRichards99 Let me know if you have any other ideas, otherwise I can push the above changes in a new PR.

**Comment by MRichards99** [comment]
Yeah I can't think of a different solution but to try and reduce the strain of the extra ICAT call, try adding a `PythonICATDistinctFieldFilter` to the list of filters passed to `get_with_pid` so the JPQL query is a bit quicker (we're not interested in the data, only if it is there or not). Don't worry if that doesn't work, but we should try minimise the extra stress where possible

**Comment by VKTB** [comment]
Closed by https://github.com/ral-facilities/datagateway-api/pull/332
