### ISSUE TITLE
Poetry has changed their installer

### ISSUE THREAD

**Issue by Reillyhewitson** [ral-facilities/datagateway-api#376]
**Description**:
Poetry 1.2 has deprecated the existing installer that is used in the readme, this installer is also recommended for previous versions. The instructions need to be changed.
See the issue poetry has about the installer being deprecated: https://github.com/python-poetry/poetry/issues/6377

**Acceptance criteria**:
- [x] Document new installation process
  - [x] New installation script
  - [x] New installation location

**Comment by neersighted** [comment]
Poetry maintainer here -- note that this is actually not directly related to 1.2 (except 1.2 was the first version to stop supporting the build infrastructure for the old installer) -- regardless of what version of Poetry you are using, https://install.python-poetry.org will support it and is strongly suggested.
