### ISSUE TITLE
Database returns timezone indicators but does not accept them

### ISSUE THREAD

**Issue by Reillyhewitson** [ral-facilities/datagateway-api#392]
**Description**:
The database backend returns times with timezone indicators e.g. `2019-01-04 01:01:01+00:00` but does not allow you to specify a timezone indicator when updating or creating an entity in strict tables mode. Pymysql will return an error calling it an `Incorrect datetime value`

**Comment by MRichards99** [comment]
DB backend to be removed as per #489
